package texconfig

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/e-chan1007/hayatex/internal/config"
	"github.com/e-chan1007/hayatex/internal/resolver"
	"github.com/e-chan1007/hayatex/internal/utils"
	"golang.org/x/sync/errgroup"
)

type FormatJob struct {
	Name     string
	Engine   string
	Patterns string
	Options  string
}

func (j *FormatJob) ToString() string {
	return fmt.Sprintf("%s %s %s %s", j.Name, j.Engine, j.Patterns, j.Options)
}

func ExecuteFormatCommands(ctx context.Context, config *config.Config, deps *resolver.TLPackageList, ce *utils.CommandExecutor) error {
	jobs := extractFormatJobs(deps)
	generateFmtutilConfig(config.TexDir, jobs)
	err := runFmtutilCommands(ctx, config, ce, jobs)
	if err != nil {
		return fmt.Errorf("Failed to execute format commands: %v", err)
	}
	return nil
}

func extractFormatJobs(deps *resolver.TLPackageList) []*FormatJob {
	var jobs []*FormatJob
	for _, pkg := range *deps {
		for _, execLine := range pkg.Executes {
			if ok, rest := utils.HasPrefixIgnoreCase(execLine, "AddFormat "); ok {
				formatJob := parseAddFormat(rest)
				if formatJob != nil {
					jobs = append(jobs, formatJob)
				}
			}
		}
	}
	return jobs
}

func generateFmtutilConfig(texdir string, jobs []*FormatJob) (string, error) {
	fmtutilDir := filepath.Join(texdir, "texmf-config", "web2c")
	if err := os.MkdirAll(fmtutilDir, 0755); err != nil {
		return "", err
	}

	fmtutilConfigPath := filepath.Join(fmtutilDir, "fmtutil.cnf")
	f, err := os.Create(fmtutilConfigPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	for _, job := range jobs {
		fmt.Fprintln(f, job.ToString())
	}

	f.WriteString("# Generated by HayaTeX\n")

	return fmtutilConfigPath, nil
}

func parseAddFormat(formatLine string) *FormatJob {
	params := utils.ParseKeyValuePairs(formatLine)

	if params["mode"] == "disabled" {
		return nil
	}

	job := &FormatJob{
		Name:     params["name"],
		Engine:   params["engine"],
		Patterns: params["patterns"],
		Options:  params["options"],
	}
	if job.Patterns == "" {
		job.Patterns = "-"
	}

	if job.Name == "" || job.Engine == "" {
		return nil
	}

	return job
}

func runFmtutilCommands(ctx context.Context, config *config.Config, ce *utils.CommandExecutor, jobs []*FormatJob) error {
	eg, ctx := errgroup.WithContext(ctx)
	semaphore := make(chan struct{}, runtime.NumCPU())

	for _, job := range jobs {
		eg.Go(func() error {
			semaphore <- struct{}{}
			defer func() { <-semaphore }()
			destDir := filepath.Join(config.TexDir, "texmf-var", "web2c", job.Engine)
			if err := os.MkdirAll(destDir, 0755); err != nil {
				return err
			}
			args := []string{
				"-ini",
				"-jobname=" + job.Name,
				"-progname=" + job.Name,
			}
			if job.Options != "" {
				args = append(args, strings.Fields(job.Options)...)
			}
			patternFile := strings.TrimPrefix(job.Patterns, "*")
			if patternFile != "" && patternFile != "-" {
				args = append(args, patternFile)
			}
			cmd := ce.NewCommandContext(ctx, job.Engine, args...)
			cmd.Dir = destDir
			return cmd.Run()
		})
	}
	return eg.Wait()
}
