package texconfig

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/e-chan1007/hayatex/internal/resolver"
	"github.com/e-chan1007/hayatex/internal/utils"
)

func GenerateFmtutilConfig(texdir string, deps *resolver.TLDatabase) (string, error) {
	fmtutilDir := filepath.Join(texdir, "texmf-config", "web2c")
	if err := os.MkdirAll(fmtutilDir, 0755); err != nil {
		return "", err
	}

	fmtutilConfigPath := filepath.Join(fmtutilDir, "fmtutil.cnf")
	f, err := os.Create(fmtutilConfigPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	f.WriteString("# Generated by HayaTeX\n")

	for _, pkg := range *deps {
		for _, execLine := range pkg.Executes {
			if ok, rest := utils.HasPrefixIgnoreCase(execLine, "AddFormat "); ok {
				line := parseAddFormat(rest)
				if line != "" {
					fmt.Fprintln(f, line)
				}
			}
		}
	}
	return fmtutilConfigPath, nil
}

func parseAddFormat(formatLine string) string {
	params := utils.ParseKeyValuePairs(formatLine)

	if params["mode"] == "disabled" {
		return ""
	}

	name := params["name"]
	engine := params["engine"]
	patterns := params["patterns"]
	if patterns == "" {
		patterns = "-"
	}
	options := params["options"]

	if name == "" || engine == "" {
		return ""
	}

	return fmt.Sprintf("%s %s %s %s", name, engine, patterns, options)
}
