package texconfig

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/e-chan1007/hayatex/internal/resolver"
	"github.com/e-chan1007/hayatex/internal/utils"
)

type LanguageJob struct {
	Name           string
	File           string
	LeftHyphenMin  string
	RightHyphenMin string
	Synonyms       []string
}

func GenerateLanguageConfig(texdir string, deps *resolver.TLDatabase) error {
	langDir := filepath.Join(texdir, "texmf-var", "tex", "generic", "config")
	if err := os.MkdirAll(langDir, 0755); err != nil {
		return err
	}

	var jobs []LanguageJob
	for _, pkg := range *deps {
		for _, execLine := range pkg.Executes {
			if ok, rest := utils.HasPrefixIgnoreCase(execLine, "AddHyphen "); ok {
				params := utils.ParseKeyValuePairs(rest)
				job := LanguageJob{
					Name:           params["name"],
					File:           params["file"],
					LeftHyphenMin:  params["lefthyphenmin"],
					RightHyphenMin: params["righthyphenmin"],
				}
				if syns := params["synonyms"]; syns != "" {
					job.Synonyms = strings.Split(syns, ",")
				}
				if job.Name != "" && job.File != "" {
					jobs = append(jobs, job)
				}
			}
		}
	}

	if err := writeLanguageDat(filepath.Join(langDir, "language.dat"), jobs); err != nil {
		return err
	}
	if err := writeLanguageDef(texdir, filepath.Join(langDir, "language.def"), jobs); err != nil {
		return err
	}
	if err := writeLanguageLua(filepath.Join(langDir, "language.dat.lua"), jobs); err != nil {
		return err
	}

	return nil
}

func writeLanguageDat(path string, jobs []LanguageJob) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "% Generated by HayaTeX")
	for _, j := range jobs {
		fmt.Fprintf(f, "%s %s\n", j.Name, j.File)
		for _, s := range j.Synonyms {
			fmt.Fprintf(f, "=%s\n", s)
		}
	}
	return nil
}

func writeLanguageDef(texdir string, path string, jobs []LanguageJob) error {
	templatePath := filepath.Join(texdir, "texmf-dist", "tex", "generic", "config", "language.def")
	var header string
	if f, err := os.Open(templatePath); err == nil {
		defer f.Close()
		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			if strings.HasPrefix(line, "%") {
				header += line + "\n"
			} else {
				break
			}
		}
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, header)
	fmt.Fprintln(f, "%% Generated by HayaTeX")
	for _, j := range jobs {
		lmin := j.LeftHyphenMin
		if lmin == "" {
			lmin = "2"
		}
		rmin := j.RightHyphenMin
		if rmin == "" {
			rmin = "3"
		}
		fmt.Fprintf(f, "\\addlanguage{%s}{%s}{}{%s}{%s}\n", j.Name, j.File, lmin, rmin)
		for _, s := range j.Synonyms {
			fmt.Fprintf(f, "\\addlanguage{%s}{%s}{}{%s}{%s}\n", s, j.File, lmin, rmin)
		}
	}
	return nil
}

func writeLanguageLua(path string, jobs []LanguageJob) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "-- Generated by HayaTeX")
	fmt.Fprintln(f, "return {")
	for _, j := range jobs {
		lmin := j.LeftHyphenMin
		if lmin == "" {
			lmin = "2"
		}
		rmin := j.RightHyphenMin
		if rmin == "" {
			rmin = "3"
		}

		fmt.Fprintf(f, "  ['%s'] = {\n", j.Name)
		fmt.Fprintf(f, "    loader = '%s',\n", j.File)
		fmt.Fprintf(f, "    lefthyphenmin = %s,\n", lmin)
		fmt.Fprintf(f, "    righthyphenmin = %s,\n", rmin)
		if len(j.Synonyms) > 0 {
			fmt.Fprintf(f, "    synonyms = { '%s' },\n", strings.Join(j.Synonyms, "', '"))
		} else {
			fmt.Fprintln(f, "    synonyms = { },")
		}
		fmt.Fprintln(f, "  },")
	}
	fmt.Fprintln(f, "}")
	return nil
}
