package texconfig

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/e-chan1007/hayatex/internal/resolver"
)

var updMapType = map[string]string{
	"addmap":      "Map",
	"addkanjimap": "KanjiMap",
	"addmixedmap": "MixedMap",
}

type MapGroup struct {
	TargetDir string
	FileName  string
	Includes  []string
}

var outputDefinitions = []MapGroup{
	{TargetDir: "dvips", FileName: "psfonts.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "dvips", FileName: "psfonts_t1.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "dvips", FileName: "psfonts_pk.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "dvips", FileName: "ps2pk.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "pdftex", FileName: "pdftex.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "pdftex", FileName: "pdftex_dl14.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "pdftex", FileName: "pdftex_ndl14.map", Includes: []string{"Map", "MixedMap"}},
	{TargetDir: "dvipdfmx", FileName: "kanjix.map", Includes: []string{"KanjiMap"}},
}

func loadUpdmapVars(texdir string) map[string]string {
	vars := make(map[string]string)
	hdrPath := filepath.Join(texdir, "texmf-dist", "web2c", "updmap-hdr.cfg")

	f, err := os.Open(hdrPath)
	if err != nil {
		fmt.Println("Error reading updmap-hdr.cfg", err)
		return vars
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) >= 2 {
			vars[parts[0]] = parts[1]
		}
	}

	return vars
}

func resolveMapName(rawName string, vars map[string]string) string {
	re := regexp.MustCompile(`@(\w+)@`)

	return re.ReplaceAllStringFunc(rawName, func(match string) string {
		key := strings.Trim(match, "@")
		if val, ok := vars[key]; ok {
			return val
		}
		return match
	})
}

func generateUpdmapConfig(texdir string, deps *resolver.TLDatabase) (map[string][][]byte, error) {
	updmapDir := filepath.Join(texdir, "texmf-config", "web2c")
	if err := os.MkdirAll(updmapDir, 0755); err != nil {
		return nil, err
	}
	updmapVars := loadUpdmapVars(texdir)
	updmapConfigPath := filepath.Join(updmapDir, "updmap.cfg")
	f, err := os.Create(updmapConfigPath)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	mapPathCache := make(map[string]string)
	filepath.WalkDir(filepath.Join(texdir, "texmf-dist", "fonts", "map"), func(path string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() && strings.HasSuffix(d.Name(), ".map") {
			mapPathCache[d.Name()] = path
		}
		if err != nil {
			fmt.Println("Error walking map directory:", err)
		}
		return nil
	})
	typeContents := make(map[string][][]byte)

	fmt.Fprintln(f, "# Generated by HayaTeX")

	for _, pkg := range *deps {
		for _, execLine := range pkg.Executes {
			trimmed := strings.TrimSpace(execLine)
			lower := strings.ToLower(trimmed)

			for prefix, mapType := range updMapType {
				if strings.HasPrefix(lower, prefix) {
					mapFile := strings.TrimSpace(trimmed[len(prefix):])
					mapFile = resolveMapName(mapFile, updmapVars)
					fmt.Fprintf(f, "%s %s\n", mapType, mapFile)

					if path, ok := mapPathCache[mapFile]; ok {
						if content, err := os.ReadFile(path); err == nil {
							if len(content) > 0 && content[len(content)-1] != '\n' {
								content = append(content, '\n')
							}
							typeContents[mapType] = append(typeContents[mapType], content)
						} else {
							fmt.Printf("Warning: Could not read map file %s: %v\n", mapFile, err)
						}
					}
					break
				}
			}
		}
	}
	return typeContents, nil
}

func ExecuteUpdmap(texdir string, deps *resolver.TLDatabase) error {
	typeContents, err := generateUpdmapConfig(texdir, deps)
	if err != nil {
		return err
	}
	baseOutputDir := filepath.Join(texdir, "texmf-var", "fonts", "map", "updmap")
	for _, def := range outputDefinitions {
		outPath := filepath.Join(baseOutputDir, def.TargetDir, def.FileName)
		if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
			return err
		}

		f, err := os.Create(outPath)
		if err != nil {
			return err
		}

		fmt.Fprintf(f, "%% %s\n", def.FileName)
		fmt.Fprintf(f, "%% Generated by HayaTeX\n")

		for _, incType := range def.Includes {
			contents := typeContents[incType]
			for _, c := range contents {
				f.Write(c)
			}
		}
		f.Close()
	}

	return nil
}
