package texconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/e-chan1007/hayatex/internal/resolver"
)

var updMapType = map[string]string{
	"addmap":      "Map",
	"addkanjimap": "KanjiMap",
	"addmixedmap": "MixedMap",
}

func GenerateUpdmapConfig(texdir string, deps *resolver.TLDatabase) (string, error) {
	updmapDir := filepath.Join(texdir, "texmf-config", "web2c")
	if err := os.MkdirAll(updmapDir, 0755); err != nil {
		return "", err
	}
	updmapConfigPath := filepath.Join(updmapDir, "updmap.cfg")
	f, err := os.Create(updmapConfigPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by HayaTeX")

	for _, pkg := range *deps {
		for _, execLine := range pkg.Executes {
			trimmed := strings.TrimSpace(execLine)
			lower := strings.ToLower(trimmed)

			for prefix, mapType := range updMapType {
				if strings.HasPrefix(lower, prefix) {
					mapFile := strings.TrimSpace(trimmed[len(prefix):])
					fmt.Fprintf(f, "%s %s\n", mapType, mapFile)
					break
				}
			}
		}
	}
	return updmapConfigPath, nil
}
